### ISSUE TITLE
[PE-D][Tester B] Unable to add new person with different name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-1/tp#131]
![image.png](https://raw.githubusercontent.com/howen02/ped/main/files/3287563e-a9c0-403b-a072-d0c43fe9b8fb.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: howen02/ped#6

**Comment by angsongyee** [comment]
Not enough information given to reproduce this bug.
